### ISSUE TITLE
Feature request: custom phase shift plots

### ISSUE THREAD

**Issue by mgennari** [callum-mccracken/npsm#10]
As of right now, the custom plots can only be performed for the eigenphase shifts using the **interesting.txt** file. However, this feature would be incredibly useful (is needed by myself) for the phase shift spaghetti plots as well. Is it possible to add this functionality?

**Comment by callum-mccracken** [comment]
Should be easy to implement (as an optional thing so it doesn't break everything else), I'll take a look later tonight!

**Comment by mgennari** [comment]
> 
> 
> Should be easy to implement (as an optional thing so it doesn't break everything else), I'll take a look later tonight!

Thanks for taking a look!

**Comment by callum-mccracken** [comment]
Btw you mean when running process_nscmc_output.py right? Should have asked before implementing things but I think I have it.

Any chance you have some sample files to test the new code with? I'm looking for phase shift, eigenphase shift, ncsmc.out file, and ideally the experiment.txt file (you have my email, right?)

**Comment by callum-mccracken** [comment]
Got the email with the input files -- thanks! It should work now, so I'll close this issue but let me know if you have any further questions/concerns/requests/anything else 🙂

- In ``process_ncsm_output.py``, up near the top there's a boolean called ``make_phase_plots_too``, set that to ``True``
- Then, create ``interesting_phase.txt`` in the same way as you now do ``interesting.txt`` (I'd change that name to ``interesting_eigenphase.txt`` but it might be weird for people who don't use this change, idk but currently it's still just ``interesting.txt`` for now)
- The code will take it from there :)
