### ISSUE TITLE
Feature request: Dynamically increase N_points in the resonance fitter

### ISSUE THREAD

**Issue by pgysbers** [callum-mccracken/npsm#14]
Changing the domain of the fitter changes the number of points. If the resonance is really narrow, you can run out of points or end up with a bad fit on very few points.

**Comment by callum-mccracken** [comment]
So just to clarify what you mean here, is it

1. dynamically adjust N_points to optimize the some parameter like R^2, so you see the auto-optimized fit first

2. add a lower limit on N_points so it doesn't try to make fits on single points or something like that

(3. Something else?)

**Comment by pgysbers** [comment]
I was thinking 2, but I guess there is some limitation of how many data points there actually are within an interval. I will try the fitter again and try to clarify what type of improvement I mean.

**Comment by pgysbers** [comment]
I don't think there is anything we can do about this issue, sometimes the energy spacing is not small enough to capture particularly narrow resonances. The NCSMC calculations just need to be re-done with different parameters.
