### ISSUE TITLE
Improvements/corrections to process_ncsmc_output.py

### ISSUE THREAD

**Issue by pnavratil** [callum-mccracken/npsm#2]
1) grace files should be named .agr rather than .grdt

2) The legend in grace files should be modified:
@ s0 legend "9\S-\N3" column 8   - this gives an xmgrace error message 
Correct format:
@ s0 legend "9\S-\N3 column 8”

3) How to run fitter alone once one has cvs files etc?
This would be also helpful if some of the eigenphase shifts are not properly matched, i.e., one wants to fix them manually and then do the fit

4) How to edit the level scheme plot?

5) It would be useful to create phase shift and eigenphase shift files for each JpiT channel with no modification in addition to the files the code produces. This is useful for more in depth analysis of complicated multi-channel outputs.

6) The second bound state in the same channel is missed (e.g., 8Be  Nmax=7 iso calculation in 2+ T=0 channel)

Thanks!

**Comment by callum-mccracken** [comment]
1. "grdt" does not appear in process_ncsmc_output.py. It does appear in npsm/ncsd_python/plot_modules/plotter.py, should I change it there? I seem to remember there was some extra program that would take the grdt files we produce there and turn them into agr, but I could be wrong.

2. Edited utils.py to implement this change, maybe double-check it works now

3. Edited fitter.py to make this easier, updates are at the bottom of the file

4. There are two ways (below). Is there some other kind of editing you'd like to do? I could make that happen.

  - edit the .svg file in inkscape (or some other vector image editing program, but inkscape is free)
  - scheme_plot_manual.py is supposed to make it a bit easier to adjust everything manually: line width, particular spacing, etc. That said, it could use some work, let me know if you find anything particularly challenging to understand in there
 
5. You mean (eigen)phase files for the "un-flipped" channels? We could do that :)

6. I'm not quite sure what you mean by "missed" here, could you provide a few more details about your inputs and desired outputs?

PS thanks for raising these issues! I see it's your first issue raised on github so let us celebrate 🎉🎉

**Comment by callum-mccracken** [comment]
closing this issue since we resumed discussion in issue #3
