### ISSUE TITLE
Problems with run_transitions

### ISSUE THREAD

**Issue by pnavratil** [callum-mccracken/npsm#3]
Hi Callum,

I got back to debugging the capture calculation of 7Li(p,gamma)8Be. For the 0+0 (i.e., capture to the g.s., it works). However, there are five bound states. I did not manage to set up the calculation for the 2+0 (i.e., the first excited state) or any other excited state. The major issue is that the NCSM_E1 file was generated for the 2+1 state (#5 state) rather than for the 2+0 (#2 state). The wavefunction_NCSMC was generated correctly for the 2+0 state. Below are sequences of my runs wit different errors and my ad hoc bug fixes:

python3 run_transitions.py
Simplifying /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso
Done simplifying! Found bound states at -15.9664, -12.558, -0.621, -4.1409
Output: /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso_simplified
resultant bound states (J, pi, T)
['0 1 0', '4 1 0', '4 1 2', '8 1 0']
target bound states (J, pi, T, num, E)
[[3, -1, 1, 1, -34.5972], [1, -1, 1, 1, -34.1933], [7, -1, 1, 1, -29.4943], [5, -1, 1, 1, -26.9939], [5, -1, 1, 2, -26.1803]]
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
Traceback (most recent call last):
  File "run_transitions.py", line 167, in <module>
    executable = make_dir(res_state)
  File "run_transitions.py", line 140, in make_dir
    file_tools.make_wf_file(wavefunction_NCSMC, res_state, run_dir)
  File "/Users/navratil/Documents/fortran/npsm/cross_sections/file_tools.py", line 319, in make_wf_file
    seg_J2, seg_parity, seg_T2 = map(int, first_line.split()[1:])
ValueError: invalid literal for int() with base 10: '-0.6210'

(i) The second 2+0 bound state with energy -0.3732 MeV was not found 
(ii) The error occurs during the processing of wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr
(iii) Desired state 2 1 2 not found … This state is actually never desired. Presumably 0 1 0 ??? 

After removing the -0.3732 eigenvector from the wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr:
python3 run_transitions.py
Simplifying /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso
Done simplifying! Found bound states at -15.9664, -12.558, -0.621, -4.1409
Output: /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso_simplified
resultant bound states (J, pi, T)
['0 1 0', '4 1 0', '4 1 2', '8 1 0']
target bound states (J, pi, T, num, E)
[[3, -1, 1, 1, -34.5972], [1, -1, 1, 1, -34.1933], [7, -1, 1, 1, -29.4943], [5, -1, 1, 1, -26.9939], [5, -1, 1, 2, -26.1803]]
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
Traceback (most recent call last):
  File "run_transitions.py", line 167, in <module>
    executable = make_dir(res_state)
  File "run_transitions.py", line 140, in make_dir
    file_tools.make_wf_file(wavefunction_NCSMC, res_state, run_dir)
  File "/Users/navratil/Documents/fortran/npsm/cross_sections/file_tools.py", line 319, in make_wf_file
    seg_J2, seg_parity, seg_T2 = map(int, first_line.split()[1:])
ValueError: invalid literal for int() with base 10: '-4.1409'

The error occurs during the processing of wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr when reaching the 4+0 bound  state with energy -4.1409
Perhaps a problem with the length of the file???

After removing also the -4.1409 eigenvector from the wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr:
python3 run_transitions.py
Simplifying /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso
Done simplifying! Found bound states at -15.9664, -12.558, -0.621, -4.1409
Output: /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso_simplified
resultant bound states (J, pi, T)
['0 1 0', '4 1 0', '4 1 2', '8 1 0']
target bound states (J, pi, T, num, E)
[[3, -1, 1, 1, -34.5972], [1, -1, 1, 1, -34.1933], [7, -1, 1, 1, -29.4943], [5, -1, 1, 1, -26.9939], [5, -1, 1, 2, -26.1803]]
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
running executable!
transitions_NCSMC.exe: line 1: ����: command not found
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
Traceback (most recent call last):
  File "run_transitions.py", line 167, in <module>
    executable = make_dir(res_state)
  File "run_transitions.py", line 114, in make_dir
    ncsm_e1.make_ncsm_e1(
  File "/Users/navratil/Documents/fortran/npsm/cross_sections/ncsm_e1.py", line 252, in make_ncsm_e1
    Rp, Rn, Rm = radii[(i, j)]
KeyError: (1, 2)

(i) Here we actually do not want the executable to run automatically.
(ii) The 2+ bound state files have not been generated. It seems the radii of the 2+ state wave not been found?
(iii) We may want a switch that will allow to run a particular bound state rather than all of them in a single shot. 

After setting 
        added_radii = True
in ncsm_e1.py:
python3 run_transitions.py
Simplifying /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso
Done simplifying! Found bound states at -15.9664, -12.558, -0.621, -4.1409
Output: /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso_simplified
resultant bound states (J, pi, T)
['0 1 0', '4 1 0', '4 1 2', '8 1 0']
target bound states (J, pi, T, num, E)
[[3, -1, 1, 1, -34.5972], [1, -1, 1, 1, -34.1933], [7, -1, 1, 1, -29.4943], [5, -1, 1, 1, -26.9939], [5, -1, 1, 2, -26.1803]]
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
running executable!
transitions_NCSMC.exe: line 1: ����: command not found
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
running executable!
transitions_NCSMC.exe: line 1: ����: command not found
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
Traceback (most recent call last):
  File "run_transitions.py", line 167, in <module>
    executable = make_dir(res_state)
  File "run_transitions.py", line 140, in make_dir
    file_tools.make_wf_file(wavefunction_NCSMC, res_state, run_dir)
  File "/Users/navratil/Documents/fortran/npsm/cross_sections/file_tools.py", line 322, in make_wf_file
    assert the_chosen_one is not None
AssertionError

(i) Error in processing the wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr?
(ii) Is the problem that it is the second 2+ state even though it has T=1 while the first one was T=0?
(iii) The 2+ NCSM_E1_Afi file was generated for 2+ 1 state (state #5) rather than for 2+ 0 (state #2)!!!
(iv) The bound state wave function was the correct one for 2+0:
#  4   1   0
# 21   80   3
# -12.5580
#-0.5871306E+00 0.9627017E-02 0.1590451E-01
#  1  1  1  1  1  2  1
  0.0040   0.1127576E-05
The last line was 
 17.9960  -0.2511903E-07
&
#  4   1   2
i.e., the “# 4  1  2” is a part of the next bound state

Keeping only 0+0 and 2+0 bound states in wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr:
run_transitions.py
Simplifying /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso
Done simplifying! Found bound states at -15.9664, -12.558, -0.621, -4.1409
Output: /Volumes/Promise_Pegasus/ncsmc_run/Li7_p/ncsm_rgm_Am2_1_1.out_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso_simplified
resultant bound states (J, pi, T)
['0 1 0', '4 1 0', '4 1 2', '8 1 0']
target bound states (J, pi, T, num, E)
[[3, -1, 1, 1, -34.5972], [1, -1, 1, 1, -34.1933], [7, -1, 1, 1, -29.4943], [5, -1, 1, 1, -26.9939], [5, -1, 1, 2, -26.1803]]
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
Desired state 2 1 2 not found in /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
running executable!
transitions_NCSMC.exe: line 1: ����: command not found
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
running executable!
transitions_NCSMC.exe: line 1: ����: command not found
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Be8_n3lo-NN3Nlnl-srg2.0_Nmax6_Nmax7.20_15st_1bd_Jz1
simplifying /Users/navratil/Projects/rgm_ncsm/NCSMC/Be8/observ.Li7_NNn3lo_3NlnlcD0.7cE-0.06-srg2.0_Nmax6.20_1bd
Traceback (most recent call last):
  File "run_transitions.py", line 167, in <module>
    executable = make_dir(res_state)
  File "run_transitions.py", line 140, in make_dir
    file_tools.make_wf_file(wavefunction_NCSMC, res_state, run_dir)
  File "/Users/navratil/Documents/fortran/npsm/cross_sections/file_tools.py", line 322, in make_wf_file
    assert the_chosen_one is not None
AssertionError

Again the NCSM_E1_Afi file was generated for 2+ 1 state (state #5) rather than for 2+ 0 (state #2)!!!

I can copy the files to Cedar if you are available to look into this.

Thanks!

Cheers,
Petr

**Comment by callum-mccracken** [comment]
A summary of the problems, with less stack traces, for easier reference later once I have the code and can try to solve these bugs:

7Li(p,gamma)8Be. For the 0+0 (i.e., capture to the g.s., it works). I did not manage to set up the calculation for the 2+0 (i.e., the first excited state) or any other excited state.

The major issue is that the NCSM_E1 file was generated for the 2+1 state (#5 state) rather than for the 2+0 (#2 state). The wavefunction_NCSMC was generated correctly for the 2+0 state

line 319, in make_wf_file
seg_J2, seg_parity, seg_T2 = map(int, first_line.split()[1:])
ValueError: invalid literal for int() with base 10: '-0.6210'

(i) The second 2+0 bound state with energy -0.3732 MeV was not found

(ii) The error occurs during the processing of wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr

(iii) Desired state 2 1 2 not found … This state is actually never desired. Presumably 0 1 0 ???

line 319, in make_wf_file
seg_J2, seg_parity, seg_T2 = map(int, first_line.split()[1:])
ValueError: invalid literal for int() with base 10: '-4.1409'

The error occurs during the processing of wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr when reaching the 4+0 bound state with energy -4.1409

Perhaps a problem with the length of the file???

[note it's almost certainly not that]

ncsm_e1.py line 252, in make_ncsm_e1
Rp, Rn, Rm = radii[(i, j)]
KeyError: (1, 2)

(i) Here we actually do not want the executable to run automatically.

[Note: fixed]

(ii) The 2+ bound state files have not been generated. It seems the radii of the 2+ state wave not been found?

(iii) We may want a switch that will allow to run a particular bound state rather than all of them in a single shot.

[Note: fixed]

cross_sections/file_tools.py, line 322, in make_wf_file
assert the_chosen_one is not None
AssertionError

(i) Error in processing the wavefunction_NCSMC_pLi7_NNn3lo_3Nlnl-srg2.0_20_Nmax7_3m1m7m5m5m_15p15m_iso.agr?

(ii) Is the problem that it is the second 2+ state even though it has T=1 while the first one was T=0?

(iii) The 2+ NCSM_E1_Afi file was generated for 2+ 1 state (state #5) rather than for 2+ 0 (state #2)!!!

(iv) The bound state wave function was the correct one for 2+0:

cross_sections/file_tools.py, line 322, in make_wf_file
assert the_chosen_one is not None
AssertionError

Again the NCSM_E1_Afi file was generated for 2+ 1 state (state #5) rather than for 2+ 0 (state #2)
